# Generated by Django 5.2.6 on 2025-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
