# Generated by Django 5.2.6 on 2025-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_news_options_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
